import { readdirSync } from "fs";

function icon(name: string): Record<string, { iconPath: string }> {
  return { [`_f_${name}`]: { iconPath: `./icons/${name}.svg` } };
}

function iconFolder(name: string): Record<string, { iconPath: string }> {
  return { [`_fd_${name}`]: { iconPath: `./icons/${name}.svg` } };
}

function iconFolderGeneric(name: string): Record<string, { iconPath: string }> {
  return { [`_fd_${name}`]: { iconPath: `./icons/folder_${name}.svg` } };
}

function iconGeneric(name: string): Record<string, { iconPath: string }> {
  return { [`_${name}`]: { iconPath: `./icons/${name}.svg` } };
}

// Generate icon list from /icons folder
const array: string[] = [];
readdirSync("icons").forEach((file) => array.push(file.split(".")[0]));

const iconList: Icon = array.reduce((acc, curr) => {
  return { ...acc, [`_f_${curr}`]: { iconPath: `./icons/${curr}.svg` } };
}, {});

const icons = {
  ...iconGeneric("file"),
  ...iconGeneric("file_light"),
  ...iconGeneric("folder"),
  ...iconGeneric("folder_light"),
  ...iconGeneric("folder_open"),
  ...iconGeneric("folder_light_open"),
  ...iconGeneric("root_folder"),
  ...iconGeneric("root_folder_open"),
  ...iconGeneric("root_folder_light"),
  ...iconGeneric("root_folder_light_open"),
  ...iconFolder("admin"),
  ...iconFolder("admin_open"),
  ...iconFolder("api"),
  ...iconFolder("api_open"),
  ...iconFolder("app"),
  ...iconFolder("app_open"),
  ...iconFolder("asset"),
  ...iconFolder("asset_open"),
  ...iconFolder("client"),
  ...iconFolder("client_open"),
  ...iconFolder("component"),
  ...iconFolder("component_open"),
  ...iconFolder("composable"),
  ...iconFolder("composable_open"),
  ...iconFolder("config"),
  ...iconFolder("config_open"),
  ...iconFolder("content"),
  ...iconFolder("content_open"),
  ...iconFolder("controller"),
  ...iconFolder("controller_open"),
  ...iconFolder("database"),
  ...iconFolder("database_open"),
  ...iconFolder("dist"),
  ...iconFolder("dist_open"),
  ...iconFolder("docs"),
  ...iconFolder("docs_open"),
  ...iconFolder("font"),
  ...iconFolder("font_open"),
  ...iconFolder("github"),
  ...iconFolder("github_open"),
  ...iconFolder("global"),
  ...iconFolder("global_open"),
  ...iconFolder("helper"),
  ...iconFolder("helper_open"),
  ...iconFolder("home"),
  ...iconFolder("home_open"),
  ...iconFolder("i18n"),
  ...iconFolder("i18n_open"),
  ...iconFolder("images"),
  ...iconFolder("images_open"),
  ...iconFolder("javascript"),
  ...iconFolder("javascript_open"),
  ...iconFolder("keys"),
  ...iconFolder("keys_open"),
  ...iconFolder("layout"),
  ...iconFolder("layout_open"),
  ...iconFolder("lib"),
  ...iconFolder("lib_open"),
  ...iconFolder("locale"),
  ...iconFolder("locale_open"),
  ...iconFolder("mail"),
  ...iconFolder("mail_open"),
  ...iconFolder("middleware"),
  ...iconFolder("middleware_open"),
  ...iconFolder("mobile"),
  ...iconFolder("mobile_open"),
  ...iconFolder("model"),
  ...iconFolder("model_open"),
  ...iconFolder("node"),
  ...iconFolder("node_open"),
  ...iconFolder("packages"),
  ...iconFolder("packages_open"),
  ...iconFolder("plugin"),
  ...iconFolder("plugin_open"),
  ...iconFolder("private"),
  ...iconFolder("private_open"),
  ...iconFolder("public"),
  ...iconFolder("public_open"),
  ...iconFolder("route"),
  ...iconFolder("route_open"),
  ...iconFolder("scripts"),
  ...iconFolder("scripts_open"),
  ...iconFolder("secure"),
  ...iconFolder("secure_open"),
  ...iconFolder("server"),
  ...iconFolder("server_open"),
  ...iconFolder("services"),
  ...iconFolder("services_open"),
  ...iconFolder("shared"),
  ...iconFolder("shared_open"),
  ...iconFolder("src"),
  ...iconFolder("src_open"),
  ...iconFolder("temp"),
  ...iconFolder("temp_open"),
  ...iconFolder("template"),
  ...iconFolder("template_open"),
  ...iconFolder("test"),
  ...iconFolder("test_open"),
  ...iconFolder("theme"),
  ...iconFolder("theme_open"),
  ...iconFolder("tools"),
  ...iconFolder("tools_open"),
  ...iconFolder("utils"),
  ...iconFolder("utils_open"),
  ...iconFolder("view"),
  ...iconFolder("view_open"),
  ...iconFolderGeneric("css"),
  ...iconFolderGeneric("css_open"),
  ...iconFolderGeneric("markdown"),
  ...iconFolderGeneric("markdown_open"),
  ...iconFolderGeneric("nuxt"),
  ...iconFolderGeneric("nuxt_open"),
  ...iconFolderGeneric("sass"),
  ...iconFolderGeneric("sass_open"),
  ...iconFolderGeneric("storybook"),
  ...iconFolderGeneric("storybook_open"),
  ...iconFolderGeneric("svelte"),
  ...iconFolderGeneric("svelte_open"),
  ...iconFolderGeneric("svg"),
  ...iconFolderGeneric("svg_open"),
  ...iconFolderGeneric("typescript"),
  ...iconFolderGeneric("typescript_open"),
  ...iconFolderGeneric("vercel"),
  ...iconFolderGeneric("vercel_open"),
  ...iconFolderGeneric("vue"),
  ...iconFolderGeneric("vue_open"),
  ...iconFolderGeneric("webpack"),
  ...iconFolderGeneric("webpack_open"),
  ...iconList,
};

export default icons;
